services:
  redis:
    image: redis:7.2-alpine
    container_name: mopl-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks: # monitoring 때문에 추가
      - mopl-net

volumes:
  redis-data:

networks: # monitoring 때문에 추가
  mopl-net:
    name: mopl-net