server:
  shutdown: graceful

spring:
  main:
    web-application-type: servlet
  application:
    name: mopl-api
  profiles:
    active: local
  config:
    import:
      - optional:file:.env[.properties]
      - jpa.yaml
      - security.yaml
  threads:
    virtual:
      enabled: true

mopl:
  admin:
    enabled: ${ADMIN_ENABLED:false}
    email: ${ADMIN_EMAIL:}
    name: 관리자
    password: ${ADMIN_PASSWORD:}
