server:
  shutdown: graceful

spring:
  main:
    web-application-type: servlet
  application:
    name: mopl-api

  profiles:
    active: local

  config:
    import:
      - optional:file:.env[.properties]
      - jpa.yaml
      - security.yaml
      - storage.yaml
      - redis.yaml
      - cache.yaml

  threads:
    virtual:
      enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com.mopl.cache: DEBUG

mopl:
  admin:
    enabled: ${ADMIN_ENABLED:false}
    email: ${ADMIN_EMAIL:}
    name: 관리자
    password: ${ADMIN_PASSWORD:}
