mopl:
  jwt:
    access-token:
      secret: ${JWT_ACCESS_TOKEN_SECRET:}
      expiration: 30m
      previous-secret: ${JWT_ACCESS_TOKEN_PREVIOUS_SECRET:}
    refresh-token:
      secret: ${JWT_REFRESH_TOKEN_SECRET:}
      expiration: 7d
      previous-secret: ${JWT_REFRESH_TOKEN_PREVIOUS_SECRET:}
    max-sessions: 1
    registry-type: ${JWT_REGISTRY_TYPE:in-memory}
    refresh-token-cookie-name: REFRESH_TOKEN
  oauth2:
    frontend-redirect-uri: ${OAUTH2_FRONTEND_REDIRECT_URI:http://localhost:8080}

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope: email, profile
          kakao:
            client-id: ${KAKAO_CLIENT_ID:}
            client-secret: ${KAKAO_CLIENT_SECRET:}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

---
spring.config.activate.on-profile: prod
