server:
  port: 8081
  shutdown: graceful

websocket:
  allowed-origins: ${WEBSOCKET_ALLOWED_ORIGINS:http://localhost:*}
  broadcaster: ${WEBSOCKET_BROADCASTER:local}

spring:
  main:
    web-application-type: servlet
  application:
    name: mopl-websocket
  profiles:
    active: local
  config:
    import:
      - optional:file:.env[.properties]
      - actuator.yaml
      - jpa.yaml
      - logging.yaml
      - redis.yaml
      - security.yaml
      - storage.yaml
  threads:
    virtual:
      enabled: true
